# rewritten for Server 2.x

version: 2

jobs:
  before_on_hold:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Before On-Hold"
  after_on_hold:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "After On-Hold"
  hold:
    type: approval

workflows:
  version: 2
  build_and_test:
    jobs:
      - before_on_hold
      - hold:
          requires:
            - before_on_hold
      - after_on_hold:
          requires:
            - hold 
